/**
 * GET /api/incidents
 *
 * Returns incidents generated by the deterministic detection engine.
 * Supports query parameters:
 * - status: 'OPEN' | 'RESOLVED' | 'ACKNOWLEDGED'
 * - type: 'LEAK' | 'CLEANING_THRESHOLD' | 'SENSOR_FAULT'
 * - priority: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL'
 * - zone_code: e.g. "T2-R03"
 * - zone_id: zone UUID
 * - limit: default 50, max 200
 */

const express = require('express');
const router = express.Router();
const { supabase } = require('../../db/supabaseClient');

router.get('/', async (req, res, next) => {
  try {
    if (!supabase) {
      return res.status(503).json({ error: 'Supabase client not configured' });
    }

    const limit = Math.min(Math.max(parseInt(req.query.limit, 10) || 50, 1), 200);
    const { status, type, priority, zone_code, zone_id } = req.query;

    let targetZoneId = zone_id;
    if (!targetZoneId && zone_code) {
      const { data: zone } = await supabase
        .from('zones')
        .select('id')
        .eq('code', zone_code)
        .single();
      if (zone) targetZoneId = zone.id;
    }

    let query = supabase
      .from('incidents')
      .select(`
        id,
        type,
        status,
        priority,
        detected_at,
        resolved_at,
        details,
        zone:zones(id, code, name, traffic_tier),
        sensor:sensors(id, code, sensor_type)
      `)
      .order('detected_at', { ascending: false })
      .limit(limit);

    if (status) query = query.eq('status', status.toUpperCase());
    if (type) query = query.eq('type', type.toUpperCase());
    if (priority) query = query.eq('priority', priority.toUpperCase());
    if (targetZoneId) query = query.eq('zone_id', targetZoneId);

    const { data, error } = await query;
    if (error) throw error;

    const formatted = (data || []).map(inc => ({
      incident_id: inc.id,
      type: inc.type,
      zone: inc.zone ? {
        id: inc.zone.id,
        code: inc.zone.code,
        name: inc.zone.name,
        traffic_tier: inc.zone.traffic_tier,
      } : null,
      sensor: inc.sensor ? {
        id: inc.sensor.id,
        code: inc.sensor.code,
        type: inc.sensor.sensor_type,
      } : null,
      priority: inc.priority,
      status: inc.status,
      detected_time: inc.detected_at,
      resolved_time: inc.resolved_at || null,
      details: inc.details || {},
    }));

    res.json({
      count: formatted.length,
      data: formatted,
    });
  } catch (err) {
    next(err);
  }
});

module.exports = router;
